@startuml

!include ../style.iuml

!include managedcontract.iuml

title AccountManager

class AccountManager << Contract >> {
  __
  +registerStudent(account: address, name: string, matrNr: uint)
  +registerSupervisor(account: address, name: string, uaccountID: string)
  .. Events ..
  +RegisteredStudent(address, string, uint)
  +RegisteredSupervisor(address, string, string)
  .. Modifiers ..
  #accountNotRegisteredYet(account: address)
}

AccountManager -down-|> ManagedContract

hide ContractManager


@enduml
