@startuml

!include contractmanager.iuml

title ManagedContract

class ManagedContract << Contract >> {
  #MAN: address
  __
  +setContractManagerAddress(contractManagerAddress: address) : bool
  .. Modifier ..
  #permission(permittedSender: bytes32)
}

ManagedContract .right.> ContractProvider : << uses >>
ManagedContract -up-> ContractManager

hide Owned

@enduml