@startuml

!include ../style.iuml

!include managedcontract.iuml

title StudentDB

class Student << Struct >> {
  name: string
  matrNr: uint
  index: uint
  testParticipationIDs: bytes32[]
  courseParticipationIDs: bytes32[]
  studentSubmissionIDs: bytes32[]
}

class StudentDB << Contract >> {
  -indices: address[]
  -students: mapping {address => Student}
  __
  +isStudent(account: address) : bool {constant}
  +addStudent(account: address, name: string, matrNr: uint)
  +getStudent(account: address) : Tuple { name: string, matrNr: uint } {constant}
  +getStudentAt(index: uint) : Tuple { name: string, matrNr: uint } {constant}
  +getNumStudents() : uint {constant}
  .. Setter for combined values ..
  +addTestParticipationID(account: address, id: bytes32) {permission: "testparticipationdb"}
  +addCourseParticipationID(account: address, id: bytes32) {permission: "courseparticipationdb"}
  +addStudentSubmissionID(account: address, id: bytes32) {permission: "studentsubmissiondb"}
}

StudentDB -up-|> ManagedContract
StudentDB -down- Student

hide ManagedContract members

@enduml
