@startuml

!include managedcontract.iuml

title SupervisorManager

class SupervisorManager << Contract >> {
  __
  +createCourse(description: string, name: bytes32, ectsPoints: uint, helpingSupervisors: address[]) {onlySupervisor} {containsOnlySupervisors: helpingSupervisors}
  +createAssignment(description: string, maxPoints: uint, dueDate: uint, courseID: uint) {onlySupervisor} {isOwnCourse: courseID}
  +createTest(description: string, maxPoints: uint, dueDate: uint, courseID: uint, helpingSupervisors: address[]) isOwnCourse(courseID) {onlySupervisor} {containsOnlySupervisors: helpingSupervisors}
  +assess(description: string, obtainedPoints: uint, submissionID: uint) {onlySupervisor} {assessmentAllowed: submissionID}
  +getAssignmentSubmissionIDs(assignmentID: uint) : Tuple { numAssignmentSubmissions: uint, ids: uint[], bool[] assessed } {constant}
  +getTestSubmissionIDs(testID: uint) : Tuple { numTestSubmissions: uint, ids: uint[], bool[] assessed } {constant}
  .. Modifier ..
  #onlySupervisor()
  #containsOnlySupervisors(accounts: address[])
  #isOwnCourse(courseID: uint)
  #assessmentAllowed(submissionID: uint)
}

SupervisorManager -down-|> ManagedContract

hide ContractManager

@enduml
