@startuml

!include ../style.iuml

!include owned.iuml
!include contractprovider.iuml

title ContractManager

class ContractManager << Contract >> {
  +contracts: mapping {name: bytes32 => address}
  +setContract(contractName: bytes32, contractAddress: address) : bool {onlyOwner}
}

ContractManager -up-|> Owned

ContractManager .down.|> ContractProvider

@enduml
