@startuml

!include ../style.iuml

!include managedcontract.iuml

title SupervisorDB

class Supervisor << Struct >> {
  name: string
  uaccountID: string
  index: uint
  courseSupervisionIDs: bytes32[]
  testSupervisionIDs: bytes32[]
  supervisorAssessmentIDs: bytes32[]
}

class SupervisorDB << Contract >> {
  -indices: address[]
  -supervisors: mapping {address => Supervisor}
  __
  +isSupervisor(account: address) : bool {constant}
  +addSupervisor(account: address, name: string, uaccountID: string)
  +getSupervisor(account: address) : Tuple { name: string, uaccountID: string } {constant}
  +getSupervisorAt(index: uint) : Tuple { name: string, uaccountID: string } {constant}
  +getNumSupervisors() : uint {constant}
  .. Setter for combined values ..
  +addCourseSupervisionID(account: address, id: bytes32) {permission: "coursesupervisiondb"}
  +addTestSupervisionID(account: address, id: bytes32) {permission: "testsupervisiondb"}
  +addSupervisorAssessmentID(account: address, id: bytes32) {permission: "supervisorassessmentdb"}
}

SupervisorDB -up-|> ManagedContract
SupervisorDB -down- Supervisor

hide ManagedContract members

@enduml
